Ft implement jwt 162473931
Amoswachira/IRepoterv2 pull request #9
Opened 2018-12-13 08:08 UTC by Amoswachira

#### What does this PR do?
Implements jwt (json web Token)
#### Description of Task to be completed?
Have the following endpoints working
The following is a protected route and only logged in users are allowed 
GET  /api /v2/test
#### How should this be manually tested?
Clone the repo cd into IRepoter
make virtual environment
install the requirements.txt file
Then run the flask run command
using postman navigate to the above url 
Then in the Authorization Tab select the Bearer token in the drop down 
Then in the Token field enter the access token 
Then hit send to access the protected route
#### What are the relevant pivotal tracker stories?
#162473931
#### Screenshots (if appropriate)
![protected route](https://user-images.githubusercontent.com/17140636/49924420-556db400-fec7-11e8-9c3b-06e2ecfca3fa.JPG)

2018-12-13 09:01 UTC, thoth-ky requested changes
Nice work. Kindly check suggested changes

2018-12-13 09:01 UTC, thoth-ky commented on app/api/v2/models.py
> +        cursor.execute("SELECT password FROM users\
don't check users passwords

2018-12-13 09:01 UTC, thoth-ky commented on app/api/v2/views.py
> +        valid_data = db.register_user(username, password, email)
```suggestion
        valid_data = db.validate_user_details(username, password, email)
```

2018-12-13 09:01 UTC, thoth-ky commented on app/api/v2/views.py
> +        data = request.get_json(silent=True)
```suggestion
        data =  parser.parse_args()
```

2018-12-13 09:01 UTC, thoth-ky commented on app/api/v2/views.py
> +            access_token = create_access_token(identity=password)
Don't use password to create access token, you can use email, username, uder_id. Do this is after actual registration

2018-12-13 09:01 UTC, thoth-ky commented on app/api/v2/views.py
> +        return {"message": "Bad credentials.Signup failed"}, 400
```suggestion
        return {"message": "Bad credentials. Signup failed"}, 400
```

2018-12-13 09:01 UTC, thoth-ky commented on app/api/v2/views.py
> +        data = request.get_json(silent=True)
```suggestion
        data = parser.parse_args()
```

2018-12-13 09:01 UTC, thoth-ky commented on app/api/v2/views.py
> +        username = data["username"]
```suggestion
        username, password = data["username"], data["password"]
```

2018-12-13 09:01 UTC, thoth-ky commented on app/api/v2/views.py
> +        valid_data = db.login_user(username, password)
```suggestion
        valid_login = db.login_user(username, password)
```

2018-12-13 09:01 UTC, thoth-ky commented on app/api/v2/views.py
> +            access_token = create_access_token(identity=password)
use username, or id or email not password here

2018-12-14 11:56 UTC, Amoswachira commented on app/api/v2/models.py
> +        cursor.execute("SELECT password FROM users\
fixed

2018-12-14 12:08 UTC, merged